### ISSUE TITLE
I forked the project to make an equivalent one that works with Q

### ISSUE THREAD

**Issue by arieljannai** [overlookmotel/fs-extra-promise#10]
If someone want it:
https://github.com/arieljannai/fs-extra-q-promise

Unless there's a plan to support other promise libraries except Bluebird, in that case there's no reason to also have the one I changed

**Comment by overlookmotel** [comment]
@arieljannai Great stuff. Sounds like it'd be worthwhile releasing your fork on npm for Q users.

Only a couple of suggestions:
1. I think `fs-extra-q` would be a better name. I plan at some point to alter this module so it uses native promises, and release `fs-extra-bluebird` for people who want to use bluebird. So then `fs-extra-q` would be consistent.
2. Could you substitute your name for mine in the `author` field of `package.json`?

**Comment by overlookmotel** [comment]
Please let me know when you've published to npm. I'll leave this issue open in the meantime.

**Comment by arieljannai** [comment]
It's already published with the name of the library, I will re publish it with the new name and the author field change

**Comment by overlookmotel** [comment]
Thanks for taking my advice on the naming. Depending on when you published `fs-extra-q-promise` to npm yesterday, you may be able to unpublish it. npm I think allows unpublishing within 24 hours.

That would avoid having two npm modules with different names doing the same thing!

**Comment by arieljannai** [comment]
I wasn't able to delete it, so I marked it as deprecated (hope it worked)

New: [NPM](https://www.npmjs.com/package/fs-extra-q) | [GitHub](https://github.com/arieljannai/fs-extra-q).

Old: [NPM](https://www.npmjs.com/package/fs-extra-q-promise)

**Comment by overlookmotel** [comment]
Brilliant! Excellent that there's a nice option for users of Q now. Nice work!
