### ISSUE TITLE
Weird bug: promisify .readJson individually fixes problems

### ISSUE THREAD

**Issue by louwers** [overlookmotel/fs-extra-promise#2]
I was surprised to see that fs-extra-promise promisifies methods individually, because I am experiencing problems with the .readJson method from fs-extra-promise, but the problem goes away if I use the fs package and promisify that method individually. See my thread at https://github.com/jprichardson/node-fs-extra/issues/156

Is someone able to reproduce my problem and figure out what is going on?

Note that I am using promises with async/await functions in Babel. That shouldn't matter though.

**Comment by overlookmotel** [comment]
Why'd you close this issue? Did you work it out?

**Comment by louwers** [comment]
Yes! Well, someone did. See https://github.com/jprichardson/node-fs-extra/issues/156 :-)
