### ISSUE TITLE
moveAsync missing from TypeScript definition

### ISSUE THREAD

**Issue by CWSpear** [overlookmotel/fs-extra-promise#20]
I don't know if this is the right place to report it, but the `moveAsync` definition is missing from TypeScript.

**Comment by CWSpear** [comment]
Specifically, I think this is what's missing:

```ts
export declare function moveAsync(src: string, dest: string): Promise<void>;
export declare function moveAsync(src: string, dest: string, options: MoveOptions): Promise<void>;
```

**Comment by CWSpear** [comment]
And need to add `MoveOptions` to the `import { ... } from 'fs-extra';`

**Comment by overlookmotel** [comment]
@CWSpear I'm afraid I don't know anything about Typescript. I don't use it myself and so it must be someone else who maintains the typescript bindings.

If you are using this: https://www.npmjs.com/package/@types/fs-extra-promise

Then looks like this is where the typing appear on Github: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/fs-extra-promise/index.d.ts

I'd suggest submitting a PR on that repo to add the lines.

Thanks!
