### ISSUE TITLE
Update fs-extra version to latest

### ISSUE THREAD

**Issue by overlookmotel** [overlookmotel/fs-extra-promise#26]
`fs-extra` used by this module is currently v0.30.0. This is now well behind - current is v2.1.2.

Need to update the dependency, but problem is that it needs checking first if any new methods have been added that need to be promisified / any sync methods that need to be excepted from promisification.

@CyberiumShadow, @andyhu, @rifler, @ReFruity you all expressed interest in the update in PR https://github.com/overlookmotel/fs-extra-promise/pull/21. Would any of you have any time to investigate.

I'm really keen to get this done, but completely tied up and not sure when I'll get to it myself.

**Comment by CyberiumShadow** [comment]
@overlookmotel Looking into it atm.

**Comment by CyberiumShadow** [comment]
@overlookmotel afaik, nothing needs to be added apart from `moveSync()` https://github.com/jprichardson/node-fs-extra/issues/309 and https://github.com/jprichardson/node-fs-extra/pull/381

`walk()` and `walkSync()` are gone from fs-extra

Other than that, that should be it

**Comment by overlookmotel** [comment]
@CyberiumShadow Great! Thanks for looking into that. I'll release a new version with latest `fs-extra` shortly.

**Comment by overlookmotel** [comment]
Updated `fs-extra` to latest in v1.0.0, just released. It is done!

**Comment by CyberiumShadow** [comment]
\o/
