### ISSUE TITLE
Change main field to explicitly pint to file

### ISSUE THREAD

**Issue by CxRes** [overlookmotel/fs-extra-promise#6]
Please change `main` in `package.json` to `./lib/index` like in fs-extra library. JSPM does not seem to like an implicit reference even though there is nothing wrong with it.

**Comment by overlookmotel** [comment]
Hi @CxRes.

Have made this change in v0.2.1, just published on npm.

But can you please raise this as an issue with JSPM? Many other modules may have the same problem (including all the ones I've written).

**Comment by CxRes** [comment]
@overlookmotel - thanks for the update. I made a ticket with Systemjs systemjs/systemjs#760, which turns out to be tracked in another repo jspm/npm#91. Hopefully, it will be resolved soon.

**Comment by overlookmotel** [comment]
@CxRes OK great. Would you mind letting me know when it's been resolved, so I can safely change it back to `./lib/`?

**Comment by CxRes** [comment]
I'll try my best to remember to remind you :). I wonder if there is a reason to prefer `./lib/`

**Comment by overlookmotel** [comment]
Thanks @CxRes. No particular reason to prefer `./lib/` I suppose - just that's how I've written all my modules so I'd like to keep it standardized. I `./lib/` seems neater to me. We all have our little fetishes I guess...
